# klucze.py

ALFA26 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

KLUCZ_ATBASZ = "ZYXWVUTSRQPONMLKJIHGFEDCBA"
KLUCZ_ROT13 = "NOPQRSTUVWXYZABCDEFGHIJKLM"
KLUCZ_GADERYPOLUKI = "GBCEDFAHKJIUMNPOQYSTLVWXRZ"


def klucz_cezara(shift: int):
    shift %= len(ALFA26)
    return ALFA26[shift:] + ALFA26[:shift]